project:
  type: website

website:
  title: "Australia-Aotearoa Consortium for Epidemic Forecasting & Analytics"
  favicon: images/ACEFA-aus-only-RGB.png
  navbar:
    logo: images/ACEFA-Logo-RGB_no_subtitle.png
    right:
      - text: "Activities"
        menu:
          - activities/decision-support.qmd
      - about.qmd
      - icon: github
        href: https://github.com/acefa-hubs
  page-footer:
    center: |
      © ACEFA, 2024 <br>
      In the spirit of reconciliation ACEFA acknowledges the Traditional Custodians throughout Australia and Aotearoa and their connections to land, waters, and community. We pay our respect to their Elders past and present and extend that respect to all Aboriginal, Torres Strait Islander and Māori peoples.

# don't re-execute code unless that code has changed
execute:
  freeze: auto

format:
  html:
    theme: 
      - yeti
      - styles.scss
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

