project:
  type: website

website:
  favicon: images/ACEFA-aus-only-RGB.png
  navbar:
    logo: images/ACEFA-Logo-RGB.png
    right:
      # - text: "Activities"
      #   menu: 
      #     - activities/winter-flu.qmd
      - about.qmd
      - icon: github
        href: https://github.com/acefa-hubs
  page-footer:
    center: |
      © ACEFA, 2024 <br>
      ACEFA acknowledges Aboriginal and Torres Strait Islander people as the Traditional Custodians of the lands on which we work and live, and pays respect to their Elders, past and present

# don't re-execute code unless that code has changed
execute:
  freeze: auto

format:
  html:
    theme: 
      - yeti
      - styles.scss
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

