---
title: "About"
title-block-banner: "#3f78a3"
title-block-banner-color: white
toc: false
sidebar: false
---

ACEFA aims to support the timely, effective response to epidemic diseases in Australia through real-time data analytics, modelling, and forecasting. Our work builds on a national seasonal influenza forecasting program (2014–19) and [COVID-19 situational assessment consortium (2020–23)](https://doi.org/10.26188/24845328.v1).

### Team

ACEFA involves multiple academic research groups from across Australia, including:

* [Infectious Disease Dynamics Unit](https://mspgh.unimelb.edu.au/research-groups/centre-for-epidemiology-and-biostatistics-research/infectious-disease-dynamics), Centre for Epidemiology and Biostatistics Research, the University of Melbourne
* [Infectious Disease Ecology and Modelling Teama](https://www.thekids.org.au/our-research/brain-and-behaviour/child-health-analytics-research-program/infectious-disease-ecology-and-modelling/), Child Health Analytics Research Program, The Kids Research Institute Australia
* [Defence Science and Technology Group](https://www.dst.defence.gov.au/) 
* Monash University
* [Infectious Disease Dynamics and Interventions Group](https://www.unsw.edu.au/medicine-health/our-schools/population-health/research/research-programs-projects/infectious-disease-dynamics-and-interventions), School of Population Health, University of New South Wales
* [Infectious Disease Epidemiology and Modelling](https://nceph.anu.edu.au/research/groups/infectious-disease-epidemiology-and-modelling), National Centre for Epidemiology and Population Health, Australian National University
* [Infectious diseases modelling and Epidemiology Group](https://www.aithm.jcu.edu.au/professor-emma-mcbryde/), Australian Institute of Tropical Health and Medicine, James Cook University
* and [Adelaide Data Science Centre](https://set.adelaide.edu.au/adelaide-data-science-centre/), University of Adelaide

as well as international partners:

* [School of Mathematics and Statistics](https://www.canterbury.ac.nz/study/academic-study/engineering/schools-and-departments-engineering-forestry-product-design/school-of-mathematics-and-statistics), University of Canterbury.
 

### Contact Us

+-----------------------------------------+---------------------------------------------------+--------------------------------------------+
| **Freya Shearer** \                     | **Nick Golding** \                                | **James Wood** \                           |
| University of Melbourne, Melbourne, VIC\| The Kids Research Institute Australia, Perth, WA \| University of New South Wales, Sydney, NSW\|
| freya.shearer [at] unimelb.edu.au       | nick.golding [at] thekids.org.au                  | james.wood [at] unsw.edu.au                | 
+-----------------------------------------+---------------------------------------------------+--------------------------------------------+


